services:
  db:
    image: postgres:16
    container_name: starburger-db
    environment:
      POSTGRES_DB: starburger
      POSTGRES_USER: starburger_user
      POSTGRES_PASSWORD: starburger_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: starburger-backend
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
      - bundles_data:/app/bundles
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://starburger_user:starburger_password@db:5432/starburger
    depends_on:
      - db
      - frontend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: starburger-frontend
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - bundles_data:/app/bundles
    working_dir: /app

  nginx:
    image: nginx:1.27-alpine
    container_name: starburger-nginx
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/staticfiles
      - media_data:/media

volumes:
  postgres_data:
  media_data:
  static_data:
  bundles_data:
