# Generated by Django 5.2.7 on 2025-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Принят'), ('COOKING', 'Готовится'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Завершён')], db_index=True, default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
