# Generated by Django 5.2.7 on 2025-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_remove_order_lat_remove_order_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ONLINE', 'Электронно')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Необработан'), ('NEW', 'Принят'), ('COOKING', 'Готовится'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Завершён')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус'),
        ),
    ]
