# Generated by Django 5.2.7 on 2025-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocodedaddress',
            name='normalized_address',
        ),
    ]
