# Generated by Django 5.2.7 on 2025-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_geocodedaddress_normalized_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedaddress',
            name='raw_address',
            field=models.CharField(max_length=255, unique=True, verbose_name='Исходный адрес'),
        ),
    ]
