# Generated by Django 5.2.7 on 2025-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_geocodedaddress_raw_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geocodedaddress',
            old_name='raw_address',
            new_name='address',
        ),
    ]
