# Generated by Django 5.2.7 on 2025-11-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Исходный адрес')),
                ('normalized_address', models.CharField(blank=True, max_length=255, verbose_name='Нормализованный адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('provider', models.CharField(default='yandex', max_length=50, verbose_name='Провайдер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Геокодированный адрес',
                'verbose_name_plural': 'Геокодированные адреса',
            },
        ),
    ]
